version: '3.9'

services:

  web:
    build: .
    container_name: web
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db


  db:
    container_name: new_db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: random@mail.ru
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5051:80"
    depends_on:
      - db

  redis:
    image: redis:7.2
    hostname: redis

  worker:
    build: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - .:/usr/src/app

  flower:
    build: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - .:/usr/src/app
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"