version: '3.9'

services:

  web:
    # билдим файл который находится в корне пути .
    build: .
    # название контейнера web
    container_name: web
    # запускаем сервер с помощью контекстного менеджера
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8000
    # указываем путь где данные будут храниться
    volumes:
      - .:/usr/src/app
#    environment:
#      - DB_HOST:db
#      - DB_NAME:postgres
#      - DB_USER:postgres
#      - DB_PASS:postgres
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db


  db:
    container_name: new_db
    image: postgres:16.2-alpine3.19
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
#    ports:
#      - "5434:5432"

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: random@mail.ru
#      PGADMIN_DEFAULT_PASSWORD: postgres
#    ports:
#      - "5051:80"
#    depends_on:
#      - db
#
  redis:
    image: redis:alpine3.19
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - .:/usr/src/app
    env_file:
      - .env.dev
    links:
      - redis
    depends_on:
      - redis
      - db

#  flower:
#    build: .
#    hostname: flower
#    entrypoint: celery
#    command: -A celery_app.app flower
#    volumes:
#      - .:/usr/src/app
#    links:
#      - redis
#    depends_on:
#      - redis
#    ports:
#      - "5555:5555"